const GETDATA_REQUEST = "getdata/request";
const GETDATA_SUCCESS = "getdata/success";
const GETDATA_FAILURE = "getdata/failure";

const GET_RESORT_DATA_REQUEST = "GET_RESORT_DATA_REQUEST";
const GET_RESORT_DATA_SUCCESS = "GET_RESORT_DATA_SUCCESS";
const GET_RESORT_DATA_FAILURE = "GET_RESORT_DATA_FAILURE";

export {
  GETDATA_REQUEST,
  GETDATA_SUCCESS,
  GETDATA_FAILURE,
  GET_RESORT_DATA_REQUEST,
  GET_RESORT_DATA_SUCCESS,
  GET_RESORT_DATA_FAILURE,
};
